# Generated by Django 6.0.3 on 2026-06-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_journalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
