# Generated by Django 6.0.3 on 2026-06-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_journalentry_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
