# Generated by Django 6.0.3 on 2026-06-15 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_birth_date_profile_gender_and_more'),
        ('teacher', '0006_alter_journalentry_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lessons', models.IntegerField(default=0, verbose_name='Всего уроков')),
                ('attended_lessons', models.IntegerField(default=0, verbose_name='Посещено уроков')),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Средний балл')),
                ('knowledge_level', models.CharField(max_length=100, verbose_name='Уровень освоения')),
                ('teacher_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий преподавателя')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='teacher.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reports', to='accounts.child')),
            ],
            options={
                'unique_together': {('group', 'student')},
            },
        ),
    ]
