# Generated by Django 6.0.3 on 2026-06-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_studentcoursereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcoursereport',
            name='teacher_comment',
        ),
    ]
