# Generated by Django 6.0.3 on 2026-06-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_remove_studentcoursereport_teacher_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Курс завершён'),
        ),
    ]
