# Generated by Django 6.0.3 on 2026-06-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_group_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentcoursereport',
            name='average_score',
        ),
    ]
