# Generated by Django 6.0.3 on 2026-06-14 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='deleted_for',
            field=models.ManyToManyField(blank=True, help_text='Пользователи, для которых чат считается удалённым (скрыт из списка)', related_name='hidden_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
