# Generated by Django 6.0.3 on 2026-06-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_attachment_chatmessage_attachment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
