# Generated by Django 6.0.3 on 2026-06-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_birth_date_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='read_notifications_data',
            field=models.TextField(blank=True, default='', verbose_name='Прочитанные уведомления'),
        ),
    ]
