# Generated by Django 6.0.3 on 2026-06-16 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_registrationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationcode',
            name='parent',
        ),
        migrations.AddField(
            model_name='registrationcode',
            name='child',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='registration_code', to='accounts.child'),
            preserve_default=False,
        ),
    ]
