# Generated by Django 6.0.3 on 2026-06-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_groups',
            field=models.PositiveIntegerField(default=6, verbose_name='Максимум групп на курс'),
        ),
        migrations.AddField(
            model_name='course',
            name='slots_per_group',
            field=models.PositiveIntegerField(default=15, verbose_name='Мест в одной группе'),
        ),
    ]
