# Generated by Django 6.0.3 on 2026-06-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_max_groups_course_slots_per_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Курс завершён'),
        ),
    ]
