# Generated by Django 6.0.3 on 2026-04-06 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_course_remove_product_category_delete_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_last_name', models.CharField(max_length=100, verbose_name='Фамилия родителя')),
                ('parent_first_name', models.CharField(max_length=100, verbose_name='Имя родителя')),
                ('parent_middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество родителя')),
                ('child_last_name', models.CharField(max_length=100, verbose_name='Фамилия ребёнка')),
                ('child_first_name', models.CharField(max_length=100, verbose_name='Имя ребёнка')),
                ('child_middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество ребёнка')),
                ('child_birth_date', models.DateField(verbose_name='Дата рождения ребёнка')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация о ребёнке')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('waiting_docs', 'Ожидание документов'), ('under_review', 'На проверке'), ('approved', 'Одобрена'), ('paid', 'Оплачена'), ('rejected', 'Отклонена')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
