# Generated by Django 6.0.3 on 2026-04-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.CreateModel(
            name='EnrollmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('parent_passport', 'Паспорт родителя'), ('snils', 'СНИЛС родителя'), ('child_birth_cert', 'Свидетельство о рождении ребёнка'), ('consent', 'Согласие на обработку данных')], max_length=30)),
                ('file', models.FileField(upload_to='enrollment_docs/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='enrollment.enrollment')),
            ],
            options={
                'unique_together': {('enrollment', 'document_type')},
            },
        ),
    ]
