# Generated by Django 6.0.3 on 2026-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_enrollment_additional_info_enrollmentdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('waiting_docs', 'Ожидание документов'), ('under_review', 'На проверке'), ('approved', 'Одобрена'), ('paid', 'Оплачена'), ('rejected', 'Отклонена')], default='waiting_docs', max_length=20),
        ),
    ]
