# Generated by Django 6.0.3 on 2026-04-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentdocument',
            name='document_type',
            field=models.CharField(choices=[('parent_passport', 'Паспорт родителя'), ('snils', 'СНИЛС родителя'), ('child_birth_cert', 'Свидетельство о рождении ребёнка')], max_length=30),
        ),
    ]
