# Generated by Django 6.0.3 on 2026-04-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_alter_enrollmentdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки на проверку'),
        ),
        migrations.AlterField(
            model_name='enrollmentdocument',
            name='document_type',
            field=models.CharField(choices=[('parent_passport', 'Паспорт родителя'), ('snils', 'СНИЛС ребенка'), ('child_birth_cert', 'Свидетельство о рождении ребёнка/Паспорт ребёнка')], max_length=30),
        ),
    ]
