# Generated by Django 6.0.3 on 2026-04-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_enrollment_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_details',
            field=models.TextField(blank=True, verbose_name='Реквизиты для оплаты'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость курса'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/%d/', verbose_name='Чек об оплате'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='receipt_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки чека'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('waiting_docs', 'Ожидание документов'), ('under_review', 'На проверке'), ('submitted', 'Ожидание'), ('approved', 'Одобрена'), ('awaiting_payment', 'Ожидает оплаты'), ('payment_review', 'Ожидает проверки оплаты'), ('paid', 'Оплачена'), ('rejected', 'Отклонена')], default='waiting_docs', max_length=20),
        ),
    ]
