# Generated by Django 6.0.3 on 2026-04-30 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_birth_date_profile_gender_and_more'),
        ('enrollment', '0006_enrollment_payment_details_enrollment_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.child'),
        ),
    ]
