# Generated by Django 6.0.3 on 2026-06-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0007_enrollment_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий/Причина отказа'),
        ),
    ]
